a = list(zip(['h', 'e', 'l', 'l', 'o'], [1, 2, 3, 4, 5]))
print(a)
b = list(zip('hello', range(1, 6)))
print(b)
print(a == b)
print("if one set is bigger than the other then zip ignores the extra values in the larger set")
c = list(zip(['h', 'e', 'l', 'l', 'o'], [1, 2, 3, 4, 5, 6]))
print(c)
print(a == c)
