print(bytearray())
print(bytearray(10))
print("Create and populate a bytearray with string: Lina")
name = bytearray(b'Lina')
print(name)
print("Use .replace method to change the L to l")
print(name.replace(b'L', b'l'))
print("Change does not persist")
print(name)
print("Confirm ends with na using .endswith method")
print(name.endswith(b'na'))
print("use .upper to make upper case")
print(name.upper())
print("use .count method to count how many letter L there are")
print(name.count(b'L'))