a = list('Hello ')
print(a)
print('########################################################################################')
a.append(100)
print(a)
print('########################################################################################')
a.extend((1, 2, 3))
print(a)
print('########################################################################################')
a.extend('...')
print(a)
print('########################################################################################')
a.clear()
print('clear a', a)
a = [1,3,5,7]
print('fill up a ', a)
print('minimum value in a', min(a))
print('maximum value in a ', max(a))
print('sum of all values in a ', sum(a))
print('length of a', len(a))
b = [6, 7, 8]
print('put value in b', b)
print('concatenate a and b ', a + b)
print('concatenate a with itself ', a * 2)
print('########################################################################################')
c = sorted(a + b)
print('concatenate a and b then sort', c)

